
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INVALID_INPUT = 2;
  public static final int SEMICOLON = 15;
  public static final int ELSE = 4;
  public static final int NOTEQ = 26;
  public static final int PLUS = 19;
  public static final int RPAREN = 9;
  public static final int INT = 6;
  public static final int LCURL = 14;
  public static final int WHILE = 5;
  public static final int RETURN = 8;
  public static final int GREATEQ = 25;
  public static final int IF = 3;
  public static final int LPAREN = 10;
  public static final int ID = 28;
  public static final int NUM = 29;
  public static final int GREAT = 23;
  public static final int COMMA = 16;
  public static final int MULT = 17;
  public static final int EOF = 0;
  public static final int LSQPAREN = 12;
  public static final int DIV = 18;
  public static final int RSQPAREN = 11;
  public static final int MINUS = 20;
  public static final int error = 1;
  public static final int LESSEQ = 24;
  public static final int EQ = 21;
  public static final int EQEQ = 27;
  public static final int RCURL = 13;
  public static final int VOID = 7;
  public static final int LESS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INVALID_INPUT",
  "IF",
  "ELSE",
  "WHILE",
  "INT",
  "VOID",
  "RETURN",
  "RPAREN",
  "LPAREN",
  "RSQPAREN",
  "LSQPAREN",
  "RCURL",
  "LCURL",
  "SEMICOLON",
  "COMMA",
  "MULT",
  "DIV",
  "PLUS",
  "MINUS",
  "EQ",
  "LESS",
  "GREAT",
  "LESSEQ",
  "GREATEQ",
  "NOTEQ",
  "EQEQ",
  "ID",
  "NUM"
  };
}

